[package]
name = "aikoql-certification"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aikoql-kernel = { path = "../kernel" }
aikoql-compiler = { path = "../compiler" }
aikoql-runtime = { path = "../runtime" }
aikoql-graph = { path = "../engines/graph" }
aikoql-storage-v2 = { path = "../storage/aikoql-v2" }
serde_json = "1"
