//! DoD 19 (HLD §52/§53): golden PDF regression suite + extraction/semantic
//! CI gate.
//!
//! Ten hand-built PDF fixtures (generated by `generate_multimodal_fixtures`,
//! checked in under `tests/fixtures/multimodal/`) run through the real
//! extraction + compilation pipeline. The output — DocumentModel, canonical
//! AST, and the full CompilationResult (fragments, IR candidates, evidence
//! trail, retrieval chunks, secret findings) — is snapshotted to JSON in
//! `tests/fixtures/multimodal/golden/{name}.json`. Any drift fails the gate.
//!
//! Update goldens after an intentional change:
//!   AIKOQL_UPDATE_GOLDENS=1 cargo test -p aikoql-ingestion \
//!       --test multimodal_golden -- --nocapture
//!
//! HLD §53: each run prints per-stage metrics (extraction / fragmentation /
//! semantic / provenance / retrieval / end-to-end) and asserts entity
//! recall against hand-annotated expectation lists — an extraction or
//! semantic regression fails even if goldens were regenerated by mistake.
//! (The Recall@K/MRR/NDCG retrieval-quality matrix lives with the existing
//! retrieval benchmarks; this gate covers pipeline regression.)

use std::collections::BTreeMap;
use std::path::Path;

const FIXTURE_DIR: &str = "tests/fixtures/multimodal";
const GOLDEN_DIR: &str = "tests/fixtures/multimodal/golden";

/// The ten HLD §52 fixtures, in the HLD's order.
const FIXTURES: &[&str] = &[
    "plain-text.pdf",
    "scanned.pdf",
    "tables.pdf",
    "complex-table.pdf",
    "charts.pdf",
    "architecture-diagram.pdf",
    "mixed-report.pdf",
    "formulas.pdf",
    "images.pdf",
    "annual-report.pdf",
];

/// HLD §53: hand-annotated recall lists — the entities a human reading each
/// fixture would annotate (a subset of what the mock analyzer may extract;
/// the golden JSON pins the full set).
fn expected_entities(name: &str) -> &'static [&'static str] {
    match name {
        "plain-text.pdf" => &["Acme Corporation", "Globex Industries"],
        "scanned.pdf" => &[],
        "tables.pdf" => &[
            "Employee Name",
            "Alice Smith",
            "Bob Johnson",
            "North America",
            "South America",
        ],
        "complex-table.pdf" => &[
            "Units Sold",
            "Product Line",
            "Industrial Sensors",
            "Home Automation",
        ],
        "charts.pdf" => &["Fiscal Quarter", "Total Revenue"],
        "architecture-diagram.pdf" => &["Client", "Gateway", "Database"],
        "mixed-report.pdf" => &[
            "Billing Pipeline",
            "Acme Corporation",
            "Billing Team",
            "Ledger Team",
            "Payment",
            "Ledger",
        ],
        "formulas.pdf" => &[],
        "images.pdf" => &[],
        "annual-report.pdf" => &[
            "Annual Report",
            "Acme Corporation",
            "Globex Industries",
            "Gamma Partners",
        ],
        _ => &[],
    }
}

fn modality_key(m: &aikoql_ingestion::FragmentModality) -> &'static str {
    match m {
        aikoql_ingestion::FragmentModality::Text => "Text",
        aikoql_ingestion::FragmentModality::Table => "Table",
        aikoql_ingestion::FragmentModality::Image => "Image",
        aikoql_ingestion::FragmentModality::Chart => "Chart",
        aikoql_ingestion::FragmentModality::Diagram => "Diagram",
        aikoql_ingestion::FragmentModality::Formula => "Formula",
        aikoql_ingestion::FragmentModality::Code => "Code",
        aikoql_ingestion::FragmentModality::Mixed => "Mixed",
    }
}

/// Extract + compile one fixture; return the stable snapshot JSON (durations
/// zeroed), the raw result (for metrics), and the document model (for
/// extraction metrics).
fn compile_fixture(
    name: &str,
) -> (
    serde_json::Value,
    aikoql_ingestion::CompilationResult,
    aikoql_ingestion::DocumentModel,
) {
    let path = Path::new(FIXTURE_DIR).join(name);
    let dm = aikoql_ingestion::extract_document(&path.to_string_lossy(), "application/pdf", None)
        .unwrap_or_else(|e| panic!("{name}: extraction failed: {e}"));
    let ast = aikoql_ingestion::document_model_to_ast(&dm);
    let result = aikoql_ingestion::compile_document_mock(&dm, &[]);

    // Keys inserted in sorted order: serde_json sorts keys by default, but
    // workspace builds unify the `preserve_order` feature from other crates,
    // which switches to insertion order — sorted insertion is identical
    // under both.
    let mut snapshot = serde_json::json!({
        "ast": serde_json::to_value(&ast).expect("ast serializes"),
        "compilation": serde_json::to_value(&result).expect("compilation serializes"),
        "document": serde_json::to_value(&dm).expect("document model serializes"),
    });
    // Wall-clock durations are machine-dependent — zero them so goldens
    // compare structure and counts only.
    if let Some(stats) = snapshot["compilation"]["stats"].as_object_mut() {
        stats.insert("total_us".into(), serde_json::json!(0));
        if let Some(phases) = stats.get_mut("phases").and_then(|p| p.as_array_mut()) {
            for phase in phases {
                if let Some(p) = phase.as_object_mut() {
                    p.insert("duration_us".into(), serde_json::json!(0));
                }
            }
        }
    }
    (snapshot, result, dm)
}

/// Semantic equality for golden comparison: objects order-insensitive,
/// floats compared with a relative epsilon wide enough for the f32
/// shortest-round-trip through the golden file (≤2⁻²⁸ relative), everything
/// else exact.
fn values_equal(a: &serde_json::Value, b: &serde_json::Value) -> bool {
    match (a, b) {
        (serde_json::Value::Object(x), serde_json::Value::Object(y)) => {
            x.len() == y.len()
                && x.iter()
                    .all(|(k, v)| y.get(k).is_some_and(|w| values_equal(v, w)))
        }
        (serde_json::Value::Array(x), serde_json::Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(p, q)| values_equal(p, q))
        }
        (serde_json::Value::Number(x), serde_json::Value::Number(y)) => {
            match (x.as_f64(), y.as_f64()) {
                (Some(a), Some(b)) => {
                    let scale = a.abs().max(b.abs()).max(1e-30);
                    (a - b).abs() <= scale * 1e-9
                }
                _ => x == y,
            }
        }
        (x, y) => x == y,
    }
}

#[test]
fn multimodal_golden_suite() {
    let update = std::env::var("AIKOQL_UPDATE_GOLDENS").is_ok_and(|v| v == "1");
    if update {
        std::fs::create_dir_all(GOLDEN_DIR).unwrap();
    }

    for name in FIXTURES {
        let (snapshot, result, dm) = compile_fixture(name);

        // §52: golden comparison — every extraction/compilation output
        // field must stay byte-stable across code changes. Compare the
        // pretty-printed strings byte-for-byte: parsing the golden back
        // into serde_json::Value would round f32 fields through f64 and
        // flag bit-identical pipelines as drifted.
        let golden_path = Path::new(GOLDEN_DIR).join(format!("{}.json", name));
        let actual_str = serde_json::to_string_pretty(&snapshot).unwrap();
        if update {
            std::fs::write(&golden_path, &actual_str).unwrap();
            eprintln!("[GOLDEN] wrote {}", golden_path.display());
        } else {
            let expected_str = std::fs::read_to_string(&golden_path)
                .unwrap_or_else(|e| panic!("{name}: read golden {}: {e}", golden_path.display()));
            if actual_str != expected_str {
                // Not byte-identical — but that alone is not drift: JSON
                // object key order depends on whether the build unified
                // serde_json's `preserve_order` feature, and f32 fields
                // round-trip through the file with tiny f64 noise. Compare
                // semantics: order-insensitive objects, epsilon-tolerant
                // floats, exact everything else.
                let actual_value: serde_json::Value = serde_json::from_str(&actual_str).unwrap();
                let expected_value: serde_json::Value =
                    serde_json::from_str(&expected_str).unwrap();
                if values_equal(&actual_value, &expected_value) {
                    continue; // presentation-only difference
                }
                let actual_lines: Vec<&str> = actual_str.lines().collect();
                let golden_lines: Vec<&str> = expected_str.lines().collect();
                let first = actual_lines
                    .iter()
                    .zip(&golden_lines)
                    .position(|(a, g)| a != g)
                    .unwrap_or(actual_lines.len().min(golden_lines.len()));
                eprintln!("[GOLDEN-MISMATCH {name}] first diff at line {first}");
                for (i, line) in actual_lines
                    .iter()
                    .enumerate()
                    .take(first + 4)
                    .skip(first.saturating_sub(3))
                {
                    eprintln!("actual[{i}]: {line}");
                }
                for (i, line) in golden_lines
                    .iter()
                    .enumerate()
                    .take(first + 4)
                    .skip(first.saturating_sub(3))
                {
                    eprintln!("golden[{i}]: {line}");
                }
                panic!("{name}: golden snapshot drifted — regenerate with AIKOQL_UPDATE_GOLDENS=1 only after reviewing the diff");
            }
        }

        // §53: per-stage metrics — printed every run (--nocapture in CI).
        let mut modality_counts: BTreeMap<&'static str, usize> = BTreeMap::new();
        for f in &result.fragments {
            *modality_counts
                .entry(modality_key(&f.modality))
                .or_default() += 1;
        }
        eprintln!(
            "[METRIC {name}] extraction pages={} chars={} images={} | \
             fragmentation frags={} ({:?}) | semantic entities={} facts={} rels={} temporal={} \
             | provenance nodes={} | retrieval chunks={} | end2end candidates={}",
            dm.page_count,
            dm.total_chars,
            dm.pages.iter().map(|p| p.images.len()).sum::<usize>(),
            result.fragments.len(),
            modality_counts,
            result.ir.entities.len(),
            result.ir.facts.len(),
            result.ir.relations.len(),
            result.ir.temporal.len(),
            result.evidence_trail.nodes.len(),
            result.embedded_chunks.len(),
            result.ir.total_candidates(),
        );

        // §53: entity recall — expected annotations must all be extracted.
        let actual: Vec<&str> = result.ir.entities.iter().map(|e| e.name.as_str()).collect();
        let missing: Vec<&&str> = expected_entities(name)
            .iter()
            .filter(|e| !actual.contains(e))
            .collect();
        assert!(
            missing.is_empty(),
            "{name}: entity recall failed — missing {missing:?} (extracted: {actual:?})"
        );
    }
}
