#!/usr/bin/env python3
"""The single release-version change point.

Cargo.toml's `[workspace.package] version` is the ONE source of truth for
the release version. Every other place that carries the number is an owned
pin listed in PINNED below; this script derives them all from that one
value.

Usage:
  python scripts/bump-version.py NEW_VERSION   # rewrite every owned pin
  python scripts/bump-version.py --check       # exit 1 if any pin drifted

The bump ritual is then: edit the ONE line in Cargo.toml (or let this
script rewrite it via --source too) -> run this -> the gates. A pin site
that this script does not know about is protected by check-sdk-compat.sh
(SDK constants) and release.yml validate-versions (manifests, website).

Deliberately NOT pinned (each for a reason):
  - CHANGELOG.md, docs/version-compatibility.md: hand-authored history rows
  - Cargo.lock / cargo-managed files: regenerated by the build
  - fuzz seeds and red-archive logs: frozen historical inputs
  - release.yml comments, benchmark comments: history
  - SDK client identities (pom filtering, package.json read, ldflags,
    importlib.metadata): derived from each build system, not literals
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Every file whose content carries the release version and must move with
# it. One line per file: (repo-relative path, minimum expected occurrences).
PINNED = [
    ("protocol/compatibility.json", 1),
    (".claude-plugin/plugin.json", 1),
    ("npm-publish/package.json", 1),
    ("crates/sdk/go/aikoql.go", 1),
    ("crates/sdk/python/python/aikoql/mcp_client.py", 1),
    ("crates/sdk/rust/src/client.rs", 1),
    ("crates/sdk/typescript/src/client.ts", 1),  # MIN only
    ("crates/sdk/typescript/package.json", 1),
    ("crates/sdk/typescript/package-lock.json", 1),
    ("crates/sdk/java/src/main/java/io/aikoql/client/AikoqlClient.java", 1),  # MIN only
    ("crates/sdk/java/pom.xml", 1),
    ("crates/sdk/java/README.md", 1),
    ("website/index.html", 1),
    ("website/docs/getting-started.md", 1),
    ("QUICKSTART.md", 1),
    ("docker-compose.release.yml", 1),
]


def current_version() -> str:
    """The single source: Cargo.toml [workspace.package] version."""
    text = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    m = re.search(r"^\[workspace\.package\]\s*\nversion = \"([^\"]+)\"", text, re.M)
    if not m:
        sys.exit("Cargo.toml: no [workspace.package] version found")
    return m.group(1)


def main() -> None:
    old = current_version()
    args = sys.argv[1:]
    if args == ["--check"]:
        check(old)
        print(f"all {len(PINNED)} release pins in sync at {old}")
        return
    if len(args) != 1 or args[0].startswith("-"):
        sys.exit("usage: python scripts/bump-version.py NEW_VERSION | --check")
    new = args[0]
    if new == old:
        check(old)
        print(f"already at {old} - every pin in sync, nothing to do")
        return
    changed = 0
    for rel, at_least in PINNED:
        p = ROOT / rel
        text = p.read_text(encoding="utf-8")
        n = text.count(old)
        if n < at_least:
            sys.exit(f"{rel}: expected >= {at_least} pins of {old}, found {n} - add the site to PINNED or fix the drift")
        text = text.replace(old, new)
        p.write_text(text, encoding="utf-8", newline="")
        changed += n
    print(f"bumped {old} -> {new}: {changed} pin sites across {len(PINNED)} files")
    print("next: bump Cargo.lock via cargo build, rebuild target/release/aikoql-mcp, run the gates")


def check(old: str) -> None:
    bad = 0
    for rel, at_least in PINNED:
        p = ROOT / rel
        if not p.exists():
            print(f"missing: {rel}")
            bad += 1
            continue
        n = p.read_text(encoding="utf-8").count(old)
        if n < at_least:
            print(f"drifted: {rel} carries {n} of {at_least}+ pins of {old}")
            bad += 1
    if bad:
        sys.exit(f"{bad} pin drift(s) - run bump-version.py {old} after fixing the source")
    print(f"release pins in sync at {old}")


if __name__ == "__main__":
    main()
